name: easy_flutter_charts
description: Example app for testing easy_flutter_charts
publish_to: "none" # Isso impede o Flutter de tentar publicar o exemplo no pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_flutter_charts:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
